# Generated by Django 3.1.7 on 2021-03-22 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='ssh_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='ssh_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ec2instance',
            name='ssh_user',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
