# Generated by Django 3.1.7 on 2021-03-23 02:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20210322_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2instance',
            name='api_key',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('player_count', models.IntegerField()),
                ('for_server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ec2instance')),
            ],
        ),
    ]
